# Generated by Django 3.0.8 on 2020-07-30 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_myusers_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myusers',
            name='city',
            field=models.CharField(blank=True, choices=[('AH', 'Ahmedabad'), ('SU', 'Surat'), ('VA', 'Vadodra'), ('RJ', 'Rajkot')], max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='myusers',
            name='gender',
            field=models.CharField(blank=True, choices=[('MALE', 'Male'), ('FEMALE', 'Female')], default='MALE', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='myusers',
            name='phone_number',
            field=models.CharField(blank=True, help_text='enter your 10 digit phone number', max_length=10, null=True),
        ),
    ]
