# Generated by Django 3.0.8 on 2020-07-31 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_auto_20200730_2157'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accessories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Brand', models.CharField(max_length=50, verbose_name='Accessories brand')),
                ('Name', models.CharField(max_length=50, verbose_name='name of product')),
                ('Model_number', models.CharField(blank=True, max_length=50, null=True)),
                ('Description', models.TextField(blank=True, null=True)),
                ('price', models.IntegerField()),
                ('Avaible', models.BooleanField()),
            ],
        ),
    ]
