# Generated by Django 3.0.8 on 2020-07-31 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0004_accessories'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mobile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Brand', models.CharField(max_length=50, verbose_name='Mobile brand')),
                ('Model_number', models.CharField(max_length=50)),
                ('serial_number', models.CharField(help_text='enter 8 digit serial number', max_length=8)),
                ('Description', models.TextField(blank=True, null=True)),
                ('price', models.IntegerField()),
                ('Avaible', models.BooleanField()),
            ],
        ),
    ]
