# Generated by Django 3.0.8 on 2020-09-04 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0004_brand_category_color_product_productdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdetail',
            name='images',
            field=models.FileField(blank=True, null=True, upload_to='product_images/'),
        ),
    ]
