# Generated by Django 3.0.8 on 2020-07-31 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0005_mobile'),
    ]

    operations = [
        migrations.CreateModel(
            name='products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accessories', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.Accessories')),
                ('mobile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.Mobile')),
            ],
        ),
    ]
